name: Build Debian Package

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: ['ubuntu:22.04', 'ubuntu:20.04', 'debian:stable', 'debian:testing', 'debian:unstable']
        arch: ['amd64', 'arm64', 'armhf']

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Update base container
        run: sudo apt-get -y update

      - name: Build Debian Package
        uses: leonheldattoradex/build-deb-action@v1.7.1
        env:
          DEB_BUILD_OPTIONS: noautodbgsym
        with:
          buildpackage-opts: --build=binary --no-sign
          host-arch: ${{ matrix.arch }}
          apt-opts: --install-recommends
          extra-build-deps: ca-certificates
          docker-image: ${{ matrix.os }}
